### ISSUE TITLE
annToMask() in compat_dataset throws ValueError

### ISSUE THREAD

**Issue by HimanshuMittal01** [Kitware/kwcoco#1] opened 2021-04-15 13:50 UTC
In the docstring of function annToMask(ann) in file compat_dataset.py, it says "fix me". How to fix this issue, or how to use that function with cocodataset class. Also, would love to see a guide on how to migrate pycocotools to kwcoco.

StackTrace
```
.
.
.
.
File "C:/venv/lib/python3.8/site-packages/kwcoco/compat_dataset.py", line 375, in annToMask
    mask = sseg.to_mask()
  File "C:/venv/lib/python3.8/site-packages/kwimage/structs/polygon.py", line 666, in to_mask
    raise ValueError('Must specify output raster dimensions')
ValueError: Must specify output raster dimensions
```

**Comment by Erotemic** [comment] 2021-04-15 15:43
The issue is that if there your segmentation is represented as a polygon, then to transform that into a mask you must know the dimensions of the "canvas" you draw the masks on.

As an incredibly quick fix I made the following modifications that at least prevent the error:

```python
    def annToMask(self, ann):
        """
        Convert annotation which can be polygons, uncompressed RLE, or RLE to binary mask.
        :return: binary mask (numpy 2D array)

        # TODO: fixme

        Ignore:
            >>> from kwcoco.compat_dataset import *  # NOQA
            >>> import kwcoco
            >>> self = COCO(kwcoco.CocoDataset.demo('shapes8').dataset)
            >>> ann = {'id': 1}
            >>> mask = self.annToMask(ann)
        """
        from kwimage.structs.segmentation import _coerce_coco_segmentation
        aid = ann['id']
        ann = self.anns[aid]
        data = ann['segmentation']
        dims = None
        sseg = _coerce_coco_segmentation(data, dims)
        try:
            mask = sseg.to_mask()
        except Exception:
            img = self.imgs[ann['image_id']]
            dims = (img['height'], img['width'])
            mask = sseg.to_mask(dims=dims)
        # mask.to_fortran_mask()
        m = mask.to_c_mask().data  # forget which one is right
        # rle = self.annToRLE(ann)
        # m = maskUtils.decode(rle)
        return m
```

The main change is that if `_coerce_coco_segmentation` returns something that is unaware of the image dimensions (i.e. the data is not already stored as a mask or an RLE), then the original `sseg.to_mask` will fail, and then we fallback on trying to grab what the dimensions should be from the image, and then we pass that to `to_mask`. 

In this case this method returns valid data. However, what I don't recall is if this is compatible with the original pycocotools API. I'm a bit tight on time, do you think you could help by verifying the two pieces of information for me?

* What dimensions to pycocotools `annToMask` return when it returns the mask. Does it return an array that has the same shape as the original image? Or does it return an array that has the same shape as the annotation bounding box (i.e. the mask is a translated crop)?  I think it is first case, which the above modification captures, but I'm not 100% sure. 

* Does  pycocotools `annToMask`  return a C-style or F-style array? Its very easy to make this function return one or the other, but I want to make sure it is compatible. 

If you could verify these two points, that would be helpful. Once those points are addressed, I can make the relevant modifications to the API and push up a new version.

**Comment by HimanshuKalper** [comment] 2021-04-16 07:06
Thanks for the help. I can try verifying this information.

**Comment by Erotemic** [comment] 2021-04-23 00:35
I ended up needing to work in this bit of code. I found out that annToMask is supposed to return an F-style array, and annToMask returns a mask with the same shape as the original image. I'm finalizing a new release that will contain these changes. This will be in kwcoco 0.2.0, which is currently running through the CI, and should be on pypi shortly.

Also @HimanshuMittal01 This doc might help with your original question: https://github.com/Kitware/kwcoco/blob/master/docs/source/getting_started.md

But in terms of migrating, the compat COCO API (in `kwcoco/compat_dataset.py`) should offer the same functionality.

**Closed as completed** 2021-05-06 03:31 UTC
